name: "Copilot Setup Steps"

# Validates when changed and allows manual runs from the Actions tab.
on:
  workflow_dispatch:
  push:
    paths:
      - .github/workflows/github_workflows_copilot-setup-steps.yml
  pull_request:
    paths:
      - .github/workflows/github_workflows_copilot-setup-steps.yml

jobs:
  # IMPORTANT: The job MUST be called exactly `copilot-setup-steps`.
  copilot-setup-steps:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    # Keep permissions minimal. Copilot will get its own token for later operations.
    permissions:
      contents: read

    env:
      NODE_VERSION: '20'
      EXPO_NO_TELEMETRY: '1'
      CI: 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Configure npm (non-essential tweaks)
        run: |
          npm config set fund false
          npm config set audit false

      - name: Create .env file
        run: |
          echo "SUPABASE_URL=${{ secrets.SUPABASE_URL }}" > .env
          echo "SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }}" >> .env

      - name: Install dependencies
        run: npm ci

      # Optional validation that often helps Copilot reason about types and style.
      # These are non-blocking on purpose to avoid failing the setup phase.
      - name: TypeScript typecheck (non-blocking)
        run: npx --yes typescript --version && npx tsc --noEmit
        continue-on-error: true

      - name: Lint (non-blocking)
        run: npm run -s lint
        continue-on-error: true